# Generated by Django 4.2.11 on 2026-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_contacts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
    ]
